#!/bin/bash
CLANG="/home/user/.doubao/agent_mode/workspace/toolchain/swift-5.8-RELEASE-ubuntu22.04/usr/bin/clang"
SDK="/home/user/.doubao/agent_mode/workspace/toolchain/iPhoneOS16.4.sdk"
exec "$CLANG" -target arm64-apple-ios16.0 -isysroot "$SDK" "$@"
